### ISSUE TITLE
cloudflare api token support

### ISSUE THREAD

**Issue by sixcorners** [turbot/steampipe-plugin-cloudflare#40]
**Describe the solution you'd like**
cloudflare has new "api tokens" which are different from "api keys" in that:
1. there can be more than one
2. they can have a restricted set of permissions
3. they can be named
4. they can expire

It would be nice if these were supported

**Additional context**
https://developers.cloudflare.com/fundamentals/api/get-started/

**Comment by misraved** [comment]
Thanks @sixcorners  for raising the request 👍 .

If anyone would like to attempt this issue, the API mentioned by @sixcorners  is an excellent place to start.

Please let us know in case there are questions 👍 .
